application: qiaoqiao-dev
#application: qiaoqiao-live
module: default
version: 1
threadsafe: true

runtime: go
api_version: go1 
 
handlers:
- url: /.*
  script: _go_app
  secure: always



#Deploy for showcase:  goapp serve app.yaml
#Deploy for server: goapp deploy -application qiaoqiao-dev -version 0
#Deploy for server: goapp deploy -application qiaoqiao-live -version 0